# Generated by Django 6.1.1 on 2026-10-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Documentos, Bases de Datos, Directorios', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción de la categoría', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Buscar respaldos SQL', max_length=150)),
                ('plantilla', models.CharField(help_text='Ej: site:{target} (ext:sql OR ext:bak)', max_length=255)),
                ('explicacion', models.TextField(blank=True, help_text='¿Para qué sirve este dork exactamente?', null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorks', to='generator.categoria')),
            ],
        ),
    ]
